### ISSUE TITLE
pip install fails because of missing 'pypi-readme.rst' file

### ISSUE THREAD

**Issue by gjerman** [Edinburgh-Genome-Foundry/kappagate#1]
pip install kappagate from pypi fails with the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'pypi-readme.rst'
Looks like the file is missing from the pypi archive

**Comment by Zulko** [comment]
Sorry for that, this is an issue with the manifest file, I will fix it. In the meantime you can install directly from Github with:

```
pip install git+https://github.com/Edinburgh-Genome-Foundry/kappagate.git
```

Let me know if that works.

**Comment by gjerman** [comment]
Great, thanks for the quick response

**Comment by Zulko** [comment]
I believe the PyPI version was just old, I updated it, which should solve the problem. Closing this for now, fell free to reopen any time if the problem persists.
